version: '2'

services:

### Webserver Container ###########################
    webserver:
        container_name: webserver
        build:
            context: ./
            dockerfile: Dockerfile-nginx
        ports:
           - "80:80"